# Generated by Django 4.1.5 on 2023-01-10 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_alter_persona_documento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='hobbies',
        ),
    ]
